name: Daily IPTV Workflow

on:
  schedule:
    - cron: '0 20 * * *'  # 每天凌晨4点执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily_ip_tv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests opencc-python-reimplemented aiohttp Pillow opencv-python-headless

      # 1️⃣ 下载网络源
      #- name: Download network sources
      #  run: |
      #    python scripts/download_sources.py

      # 2️⃣ 合并本地源
      - name: Merge local sources
        run: |
          python scripts/merge_local_sources.py

      # 3️⃣ 测试 IPTV 流并生成 working.m3u
      - name: Test IPTV streams
        run: |
          python scripts/test_adaptive_async_batch.py

      # 4️⃣ 提取频道
      - name: Extract regional channels
        run: |
          python scripts/extract_channels.py

      # 5️⃣ 生成 M3U 文件
      - name: Generate M3U files
        run: |
          python scripts/csv_to_m3u.py

      # 6️⃣ 提交生成文件
      - name: Commit all outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/ input/network/manual input/network/network_sources
          git commit -m "Daily update IPTV sources and M3U [skip ci]" || echo "No changes to commit"
          git push
