name: Download TV Folder

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点自动触发（可选）

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库代码
      - uses: actions/checkout@v3

      # 2️⃣ 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ 安装依赖
      - name: Install requests
        run: pip install requests

      # 4️⃣ 执行下载脚本（脚本在 scripts/ 文件夹内）
      - name: Run download script
        run: python scripts/download_tv_folder.py

      # 5️⃣ 提交并推送 png 文件夹到仓库
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add png
          git commit -m "Update tv folder" || echo "No changes"
          git push
