name: Auto Format M3U

permissions:
  contents: write

on:
  push:
    paths:
      - 'input/mysource/*.m3u'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2️⃣ 设置 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypinyin

      # 4️⃣ 运行 M3U 脚本生成 total.csv 和 total.m3u
      - name: Run M3U Formatter
        run: |
          python scripts/format_m3u.py

      # 5️⃣ 提交 total.csv 和 total.m3u 到 main 分支
      - name: Commit output files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/total.csv output/total.m3u
          git commit -m "Auto update total.csv and total.m3u" || echo "No changes to commit"
          git push
