name: Generate Final M3U

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  csv_to_m3u:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests opencc-python-reimplemented

      - name: Generate final M3U files
        run: |
          python scripts/csv_to_m3u.py

      - name: Commit & push M3U
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/*.m3u output/sum_cvs/*.csv
          git commit -m "🤖 Auto update IPTV M3U on $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push