name: Generate M3U from CSV

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点自动触发，可根据需要修改

permissions:
  contents: write  # 允许 workflow 提交文件到仓库

jobs:
  generate_m3u:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库
      - uses: actions/checkout@v3

      # 2️⃣ 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ 执行 Python 脚本
      - name: Run CSV to M3U
        run: python scripts/csv_to_m3u.py

      # 5️⃣ 提交生成的 M3U 文件
      - name: Commit and push M3U
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.m3u
          git commit -m "Update M3U files" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main