name: Generate Sum M3U

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 1 * *'  # 每月1日凌晨3点自动执行

jobs:
  generate_m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Ensure output folder exists
        run: mkdir -p output/sum_m3u

      - name: Generate M3U for each CSV
        run: |
          for csvfile in output/sum_cvs/find_hk_sum.csv \
                         output/sum_cvs/find_international_sum.csv \
                         output/sum_cvs/find_mo_sum.csv \
                         output/sum_cvs/find_taiwan_sum.csv
          do
            name=$(basename $csvfile .csv)
            python scripts/csv_to_m3u_int.py "$csvfile" "output/sum_m3u/${name}.m3u"
          done

      - name: List generated M3U files
        run: ls -l output/sum_m3u
