name: Extract International Channels

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *'  # 每月1日凌晨4点（比台湾频道晚1小时）

permissions:
  contents: write

jobs:
  extract_channels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run extract script
        run: |
          set -e
          echo "Running extract_international_channels.py..."
          python scripts/extract_international_channels.py

      - name: Check international_sum.csv hash
        run: sha256sum input/network/international_sum.csv

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: international-sum
          path: input/network/international_sum.csv

      - name: Commit & push international_sum.csv if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add input/network/international_sum.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update international_sum.csv ($(date -u '+%Y-%m-%d %H:%M:%S')) [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
