name: IPTV Auto Merge & Test (Full Flow)

# 每天凌晨4点执行（UTC+8 = 20点 UTC）
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write  # 允许推送文件

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600  # 允许长时间执行
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp

      - name: Merge sources
        run: python scripts/merge.py

      - name: Test streams (Async Full Test)
        run: python scripts/test_adaptive_async_batch.py

     # - name: Classify channels + summary
       # run: python scripts/classify.py

      - name: Commit and Push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Auto update IPTV lists" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
